FROM python:3.9-slim

# Installer les dépendances
RUN pip install influxdb-client requests

# Copier le script
COPY generate_realistic_data.py /app/generate_realistic_data.py

# Définir le répertoire de travail
WORKDIR /app

# Commande par défaut
CMD ["python", "generate_realistic_data.py"]
