services:
  router_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: router_django
    ports:
      - "8080:8080"
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_USER=user
      - SQL_PASSWORD=password
      - SQL_DATABASE=routerdb
      - DJANGO_SETTINGS_MODULE=router_supervisor.prod_settings
      - DEBUG=True
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./telegraf/sample_metrics:/tmp/metrics:rw
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy:/etc/caddy
      - static_volume:/srv/static
      - media_volume:/srv/media
    depends_on:
      - router_django

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: routerdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@telecom-sudparis.eu
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=telecom-sudparis
      - DOCKER_INFLUXDB_INIT_BUCKET=router-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=BQSixul3bdmN-KtFDG_BPfUgSDGc1ZIntJ-QYa2fiIQjA_2psFN2z21AOmxD2s8fpStGlj8YWyvTCckOeCrFJA==
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: pipeline
    environment:
      - MIBS=
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/processors.conf:/etc/telegraf.d/processors.conf:ro
      - ./telegraf/sample_metrics:/tmp/metrics:rw
    depends_on:
      - influxdb
    working_dir: /code

  telegraf:
    image: telegraf:1.35        # ← l’image officielle multi-architecture
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf:/etc/telegraf.d
      - ./telegraf/sample_metrics:/tmp/metrics:rw
    depends_on:
      - router_django
      - influxdb
    ports:
      - "57500:57500"
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc

volumes:
  pgdata:
  pgadmin_data:
  static_volume:
  media_volume:
  influxdb_data:
  influxdb_config: