#!/bin/sh
set -e

# Se déplacer dans le répertoire du projet Django
cd /code

# Démarrer Gunicorn avec fichier de configuration
exec gunicorn router_supervisor.src.wsgi:application \
    --config /code/gunicorn.conf.py