# Generated by Django 4.2.17 on 2025-01-03 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_routeur', 'migration_seuil_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du routeur')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Adresse IP du routeur')),
                ('user', models.CharField(max_length=50, verbose_name="Nom d'utilisateur sur le routeur en ssh")),
                ('password', models.CharField(max_length=100, verbose_name='Mot de passe du routeur en ssh')),
                ('secret', models.CharField(max_length=100, verbose_name='Mot de passe pour enable')),
            ],
        ),
        migrations.AlterField(
            model_name='seuil',
            name='CPU',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='CPU utilisé en %'),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='nom',
            field=models.CharField(default='seuil', max_length=50, unique=True, verbose_name='Nom du seuil'),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='ram',
            field=models.FloatField(default=300, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='RAM en Mo'),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='trafic',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Bande passante en Mo/s'),
        ),
    ]
