# Generated by Django 4.2.17 on 2025-01-01 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seuils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='RAM en Mo')),
                ('CPU', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='CPU utilisé en %')),
            ],
        ),
    ]
