# Generated by Django 4.2.17 on 2025-01-03 01:32

from django.db import migrations


def create_default_seuil(apps, schema_editor):
    Seuil = apps.get_model('config_routeur', 'Seuil')
    Seuil.objects.create(
        id=1,
        ram=300,
        CPU=50,
        trafic=100,
        nom="seuil_par_defaut"
    )


def delete_default_seuil(apps, schema_editor):
    Seuil = apps.get_model('config_routeur', 'Seuil')
    Seuil.objects.filter(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('config_routeur', '0001_routeur_alter_seuil_cpu_alter_seuil_nom_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_seuil, delete_default_seuil),
    ]

