# Generated by Django 4.2.17 on 2025-01-03 01:32

from django.db import migrations


def create_default_threshold(apps, schema_editor):
    threshold = apps.get_model('config_routeur', 'threshold')
    threshold.objects.create(
        id=1,
        ram=300,
        cpu=50,
        trafic=100,
        nom="threshold_par_defaut"
    )


def delete_default_threshold(apps, schema_editor):
    threshold = apps.get_model('config_routeur', 'threshold')
    threshold.objects.filter(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('config_routeur', '0001_routeur_alter_threshold_cpu_alter_threshold_nom_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_threshold, delete_default_threshold),
    ]

