# Generated by Django 4.2.17 on 2025-01-03 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_routeur', '0002_create_default_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeur',
            name='threshold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='config_routeur.threshold'),
        ),
    ]
