# Generated by Django 4.2.17 on 2025-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_routeur', '0003_rename_seuils_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuil',
            name='nom',
            field=models.CharField(default='seuil 1', editable=False, max_length=50, unique=True, verbose_name='Nom du seuil'),
            preserve_default=False,
        ),
    ]
