# Generated by Django 4.2.17 on 2025-01-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_routeur', '0004_threshold_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom du threshold'),
        ),
    ]
