# Generated by Django 4.2.17 on 2025-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_routeur', '0003_rename_thresholds_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='nom',
            field=models.CharField(default='threshold 1', editable=False, max_length=50, unique=True, verbose_name='Nom du threshold'),
            preserve_default=False,
        ),
    ]
