# Generated by Django 4.2.17 on 2025-03-31 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.FloatField(default=300, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='RAM in MB')),
                ('cpu', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='CPU usage in %')),
                ('trafic', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Bandwidth in MB/s')),
                ('name', models.CharField(default='threshold', max_length=50, unique=True, verbose_name='Threshold name')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Router name')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Router IP address')),
                ('user', models.CharField(max_length=50, verbose_name='SSH username for the router')),
                ('password', models.CharField(max_length=100, verbose_name='SSH password for the router')),
                ('secret', models.CharField(max_length=100, verbose_name='Enable password')),
                ('threshold', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='thresholds_app.threshold', verbose_name='Associated threshold')),
            ],
        ),
    ]
