# Generated by Django 4.2.17 on 2025-07-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'threshold',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'kpi',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('router_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_models.threshold')),
            ],
            options={
                'db_table': 'router',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('traffic', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('input_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('output_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('errors', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.router')),
            ],
            options={
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='RouterMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.router')),
            ],
            options={
                'db_table': 'router_metric_log',
            },
        ),
        migrations.CreateModel(
            name='User_Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.router')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.user')),
            ],
            options={
                'db_table': 'user_router',
            },
        ),
        migrations.CreateModel(
            name='Threshold_KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.kpi')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.threshold')),
            ],
            options={
                'db_table': 'threshold_kpi',
            },
        ),
        migrations.CreateModel(
            name='Router_Interface_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.interface')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.router')),
            ],
            options={
                'db_table': 'router_interface_log',
            },
        ),
        migrations.CreateModel(
            name='KPI_Interface_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.interface')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.kpi')),
            ],
            options={
                'db_table': 'kpi_interface_log',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('log_date', models.DateTimeField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.interface')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
        migrations.AddConstraint(
            model_name='user_router',
            constraint=models.UniqueConstraint(fields=('user', 'router'), name='unique_user_router'),
        ),
        migrations.AddConstraint(
            model_name='threshold_kpi',
            constraint=models.UniqueConstraint(fields=('threshold', 'kpi'), name='unique_threshold_kpi'),
        ),
        migrations.AddConstraint(
            model_name='router_interface_log',
            constraint=models.UniqueConstraint(fields=('router', 'interface', 'log_id'), name='unique_router_interface_log'),
        ),
        migrations.AddConstraint(
            model_name='kpi_interface_log',
            constraint=models.UniqueConstraint(fields=('interface', 'log_id', 'kpi'), name='unique_kpi_interface_log'),
        ),
        migrations.AddIndex(
            model_name='kpi_interface_log',
            index=models.Index(fields=['timestamp'], name='core_models_kpi_interface_log_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi_interface_log',
            index=models.Index(fields=['interface', 'kpi'], name='core_models_kpi_interface_log_interface_kpi_idx'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('router', 'name'), name='unique_router_interface'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('interface', 'log_id'), name='unique_interface_log_alert'),
        ),
    ]
